INSERT INTO editorial (nombre, anno_fundacion, ubicacion) VALUES 
('Tusquets', 1969, 'Barcelona, España'),
('Plaza & Janés', 1959, 'Barcelona, España'),
('Grijalbo', 1939, 'Barcelona, España'),
('Kitsune Manga', 2019, 'Madrid, España'),
('Astiberri', 2001, 'Bilbao, España'),
('Norma Editorial', 1977, 'Barcelona, España'),
('Debolsillo', 1957, 'Barcelona, España'),
('B de Bolsillo', 1986, 'Barcelona, España'),
('Salamandra', 2000, 'Barcelona, España'),
('Nova', 1990, 'Madrid, España'),
('Molino', 1933, 'Barcelona, España'),
('Planeta', 1949, 'Madrid, España'),
('Rocabolsillo', 2013, 'Barcelona, España'),
('Panini España', 1986, 'Girona, España'),
('ECC Ediciones', 2011, 'Barcelona, España'),
('Planeta Cómic', 1984, 'Barcelona, España'),
('Ivrea', 1997, 'Barcelona, España');
-- ==============================================================================
-- 2. CATEGORÍA: LIBROS (TIPO 2) - 34 Obras
-- ==============================================================================
INSERT INTO obra (titulo, descripcion, genero, anno_lanzamiento, portada, tipo, nombre_editorial) VALUES 
('El Resplandor', 'Una familia se aísla en un hotel maldito durante el invierno.', 'Terror', 1977, 'imagen/img_obras/libros/resplandor.jpg', 2, 'Plaza & Janés'),
('It (Eso)', 'Un grupo de niños enfrenta a una entidad cósmica que toma forma de payaso.', 'Terror', 1986, 'imagen/img_obras/libros/it.jpg', 2, 'Plaza & Janés'),
('Misery', 'Un escritor es secuestrado por su fan número uno tras sufrir un accidente.', 'Terror', 1987, 'imagen/img_obras/libros/misery.jpg', 2, 'Plaza & Janés'),
('Cien años de soledad', 'La historia de la familia Buendía en el pueblo ficticio de Macondo.', 'Realismo Mágico', 1967, 'imagen/img_obras/libros/100_anos.jpg', 2, 'Debolsillo'),
('El Silmarillion', 'Los mitos y leyendas de la Primera Edad de la Tierra Media.', 'Fantasía', 1977, 'imagen/img_obras/libros/silmarillion.jpg', 2, 'Plaza & Janés'),
('Harry Potter y el Cáliz de Fuego', 'Harry participa en el peligroso Torneo de los Tres Magos.', 'Fantasía', 2000, 'imagen/img_obras/libros/hp_4.jpg', 2, 'Salamandra'),
('Harry Potter y la Orden del Fénix', 'Voldemort ha regresado, pero el Ministerio de Magia lo niega.', 'Fantasía', 2003, 'imagen/img_obras/libros/hp_5.jpg', 2, 'Salamandra'),
('Harry Potter y el Misterio del Príncipe', 'Harry descubre el oscuro pasado de Voldemort a través de recuerdos.', 'Fantasía', 2005, 'imagen/img_obras/libros/hp_6.jpg', 2, 'Salamandra'),
('Harry Potter y las Reliquias de la Muerte', 'La batalla final entre las fuerzas del bien y el Señor Oscuro.', 'Fantasía', 2007, 'imagen/img_obras/libros/hp_7.jpg', 2, 'Salamandra'),
('Elantris', 'La antigua ciudad de los dioses ha caído bajo una extraña maldición.', 'Fantasía', 2005, 'imagen/img_obras/libros/elantris.jpg', 2, 'B de Bolsillo'),
('El Aliento de los Dioses', 'Dos princesas enfrentan su destino en un reino donde el color es magia.', 'Fantasía', 2009, 'imagen/img_obras/libros/warbreaker.jpg', 2, 'B de Bolsillo'),
('La Música del Silencio', 'Siete días en la misteriosa vida de Auri en la Subrealidad.', 'Fantasía', 2014, 'imagen/img_obras/libros/musica_silencio.jpg', 2, 'Debolsillo'),
('El Mesías de Dune', 'Paul Atreides se enfrenta a las consecuencias de su jihad galáctica.', 'Ciencia Ficción', 1969, 'imagen/img_obras/libros/dune_2.jpg', 2, 'Debolsillo'),
('Hijos de Dune', 'Los herederos del imperio de Atreides luchan por el poder.', 'Ciencia Ficción', 1976, 'imagen/img_obras/libros/dune_3.jpg', 2, 'Debolsillo'),
('Dios Emperador de Dune', 'Leto II gobierna el universo con puño de hierro durante milenios.', 'Ciencia Ficción', 1981, 'imagen/img_obras/libros/dune_4.jpg', 2, 'Debolsillo'),
('Yo, Robot', 'Una colección de historias sobre la evolución de la robótica positrónica.', 'Ciencia Ficción', 1950, 'imagen/img_obras/libros/yo_robot.jpg', 2, 'Debolsillo'),
('El Fin de la Eternidad', 'Una organización controla y altera la historia de la humanidad a través del tiempo.', 'Ciencia Ficción', 1955, 'imagen/img_obras/libros/fin_eternidad.jpg', 2, 'Debolsillo'),
('Cita con Rama', 'Una gigantesca nave espacial alienígena entra en el sistema solar.', 'Ciencia Ficción', 1973, 'imagen/img_obras/libros/rama.jpg', 2, 'Nova'),
('El Marciano', 'Un astronauta debe usar la ciencia para sobrevivir solo en Marte.', 'Ciencia Ficción', 2011, 'imagen/img_obras/libros/martian.jpg', 2, 'Nova'),
('Fundación e Imperio', 'El plan de Seldon es amenazado por un mutante conocido como el Mulo.', 'Ciencia Ficción', 1952, 'imagen/img_obras/libros/fundacion_2.jpg', 2, 'Debolsillo'),
('Segunda Fundación', 'La búsqueda desesperada de la misteriosa Segunda Fundación.', 'Ciencia Ficción', 1953, 'imagen/img_obras/libros/fundacion_3.jpg', 2, 'Debolsillo'),
('Hyperion', 'Siete peregrinos viajan a un planeta remoto en vísperas del Armagedón.', 'Ciencia Ficción', 1989, 'imagen/img_obras/libros/hyperion.jpg', 2, 'Plaza & Janés'),
('La Caída de Hyperion', 'La guerra estalla en la red de mundos humanos.', 'Ciencia Ficción', 1990, 'imagen/img_obras/libros/hyperion_2.jpg', 2, 'Nova'),
('Los Juegos del Hambre', 'Jóvenes son forzados a luchar a muerte en un reality show televisado.', 'Distopía', 2008, 'imagen/img_obras/libros/hg_1.jpg', 2, 'Molino'),
('En Llamas', 'La rebelión comienza a gestarse en los distritos de Panem.', 'Distopía', 2009, 'imagen/img_obras/libros/hg_2.jpg', 2, 'Molino'),
('Sinsajo', 'Katniss se convierte en el símbolo de la guerra contra el Capitolio.', 'Distopía', 2010, 'imagen/img_obras/libros/hg_3.jpg', 2, 'Molino'),
('El Archivo de las Tormentas: Esquirla del Amanecer', 'Una novela corta centrada en Rysn y una expedición a Akinah.', 'Fantasía', 2020, 'imagen/img_obras/libros/esquirla.jpg', 2, 'Nova'),
('Danza de Dragones (Parte 2)', 'El asedio a Meereen se intensifica mientras Jon Nieve lidia con la Guardia.', 'Fantasía', 2011, 'imagen/img_obras/libros/got_5_2.jpg', 2, 'Plaza & Janés'),
('Un Cuento Perfecto', 'Dos personas de mundos distintos se encuentran en el momento exacto.', 'Romance', 2020, 'imagen/img_obras/libros/cuento_perfecto.jpg', 2, 'Debolsillo'),
('La Sombra del Viento', 'Un joven descubre un libro maldito que cambiará su vida en Barcelona.', 'Misterio', 2001, 'imagen/img_obras/libros/sombra_viento.jpg', 2, 'Tusquets'),
('El Código Da Vinci', 'Un experto en simbología investiga un asesinato en el Louvre.', 'Thriller', 2003, 'imagen/img_obras/libros/codigo_davinci.jpg', 2, 'Plaza & Janés'),
('Ángeles y Demonios', 'Una antigua hermandad secreta planea destruir el Vaticano.', 'Thriller', 2000, 'imagen/img_obras/libros/angeles_demonios.jpg', 2, 'Planeta'),
('Los Pilares de la Tierra', 'La construcción de una catedral gótica en la Inglaterra del siglo XII.', 'Ficción Histórica', 1989, 'imagen/img_obras/libros/pilares_tierra.jpg', 2, 'Plaza & Janés'),
('El Médico', 'Un joven viaja a Persia en el siglo XI para aprender el arte de la medicina.', 'Ficción Histórica', 1986, 'imagen/img_obras/libros/medico.jpg', 2, 'Rocabolsillo'),
('Ojos de agua', 'Leo Caldas es asignado a la investigación del asesinato de un joven saxofonista en la costa gallega', 'Misterio', 2007, 'imagen/img_obras/libros/ojosdeagua_1.jpg', 2, 'Debolsillo');

-- ==============================================================================
-- 3. CATEGORÍA: MANGAS (TIPO 1) - 33 Obras
-- ==============================================================================
INSERT INTO obra (titulo, descripcion, genero, anno_lanzamiento, portada, tipo, nombre_editorial) VALUES 
('Neon Genesis Evangelion Vol. 1', 'Shinji es reclutado para pilotar un mecha gigante y salvar a la humanidad.', 'Mecha', 1994, 'imagen/img_obras/mangas/eva_1.jpg', 1, 'Norma Editorial'),
('Sailor Moon Vol. 1', 'Usagi Tsukino descubre que es una guerrera mágica destinada a proteger la Tierra.', 'Shojo', 1991, 'imagen/img_obras/mangas/sailormoon_1.jpg', 1, 'Norma Editorial'),
('Cardcaptor Sakura Vol. 1', 'Sakura libera accidentalmente unas cartas mágicas y debe recuperarlas.', 'Shojo', 1996, 'imagen/img_obras/mangas/sakura_1.jpg', 1, 'Norma Editorial'),
('Fruits Basket Vol. 1', 'Tohru descubre que la familia Soma se transforma en animales del zodiaco.', 'Shojo', 1998, 'imagen/img_obras/mangas/fruitsbasket_1.jpg', 1, 'Norma Editorial'),
('Nana Vol. 1', 'Dos chicas llamadas Nana comparten piso en Tokio y buscan cumplir sus sueños.', 'Josei', 2000, 'imagen/img_obras/mangas/nana_1.jpg', 1, 'Planeta Cómic'),
('Inuyasha Vol. 1', 'Kagome viaja al Japón feudal y se alía con un medio demonio.', 'Shonen', 1996, 'imagen/img_obras/mangas/inuyasha_1.jpg', 1, 'Planeta Cómic'),
('Ranma 1/2 Vol. 1', 'Ranma Saotome cambia de chico a chica al mojarse con agua fría.', 'Comedia', 1987, 'imagen/img_obras/imagen/img_obras/mangas/ranma_1.jpg', 1, 'Planeta Cómic'),
('Yu Yu Hakusho Vol. 1', 'Yusuke muere salvando a un niño y revive como detective espiritual.', 'Shonen', 1990, 'imagen/img_obras/mangas/yuyu_1.jpg', 1, 'Ivrea'),
('Rurouni Kenshin Vol. 1', 'El legendario asesino Hitokiri Battosai jura no volver a matar.', 'Shonen', 1994, 'imagen/img_obras/mangas/kenshin_1.jpg', 1, 'Norma Editorial'),
('Gintama Vol. 1', 'Samuráis y alienígenas conviven en una loca versión del periodo Edo.', 'Comedia', 2003, 'imagen/img_obras/mangas/gintama_1.jpg', 1, 'Kitsune Manga'),
('Fairy Tail Vol. 1', 'Las locas aventuras del gremio de magos más destructivo del reino de Fiore.', 'Shonen', 2006, 'imagen/img_obras/mangas/fairytail_1.jpg', 1, 'Norma Editorial'),
('Black Clover Vol. 1', 'Un chico sin magia aspira a convertirse en el Rey Mago.', 'Shonen', 2015, 'imagen/img_obras/mangas/blackclover_1.jpg', 1, 'Norma Editorial'),
('Dr. Stone Vol. 1', 'La humanidad entera se petrifica y Senku busca restaurarla con ciencia.', 'Shonen', 2017, 'imagen/img_obras/mangas/drstone_1.jpg', 1, 'Ivrea'),
('The Promised Neverland Vol. 1', 'Niños en un orfanato idílico descubren un oscuro y terrorífico secreto.', 'Shonen', 2016, 'imagen/img_obras/mangas/neverland_1.jpg', 1, 'Norma Editorial'),
('Kaguya-sama: Love is War Vol. 1', 'Dos genios orgullosos intentan hacer que el otro confiese su amor primero.', 'Comedia', 2015, 'imagen/img_obras/mangas/kaguya_1.jpg', 1, 'Ivrea'),
('Jojo Bizarre Adventure Parte 2', 'Joseph Joestar enfrenta a los Hombres del Pilar en los años 30.', 'Shonen', 1987, 'imagen/img_obras/mangas/jojo_2.jpg', 1, 'Ivrea'),
('Jojo Bizarre Adventure Parte 3', 'Jotaro viaja a Egipto para salvar a su madre del resucitado Dio.', 'Shonen', 1989, 'imagen/img_obras/mangas/jojo_3.jpg', 1, 'Ivrea'),
('Jojo Bizarre Adventure Parte 4', 'Extraños sucesos y asesinos en serie en el pacífico pueblo de Morioh.', 'Shonen', 1992, 'imagen/img_obras/mangas/jojo_4.jpg', 1, 'Ivrea'),
('Jojo Bizarre Adventure Parte 5', 'Giorno Giovanna intenta tomar el control de la mafia italiana.', 'Shonen', 1995, 'imagen/img_obras/mangas/jojo_5.jpg', 1, 'Ivrea'),
('Jojo Bizarre Adventure Parte 6', 'Jolyne Cujoh es incriminada y enviada a la prisión de Green Dolphin Street.', 'Shonen', 1999, 'imagen/img_obras/mangas/jojo_6.jpg', 1, 'Ivrea'),
('Mob Psycho 100 Vol. 1', 'Un chico con inmensos poderes psíquicos intenta llevar una vida normal.', 'Shonen', 2012, 'imagen/img_obras/mangas/mob_1.jpg', 1, 'Ivrea'),
('Assassination Classroom Vol. 1', 'Una clase tiene como tarea asesinar a su profesor, un pulpo alienígena.', 'Shonen', 2012, 'imagen/img_obras/mangas/assclass_1.jpg', 1, 'Panini España'),
('Soul Eater Vol. 1', 'Estudiantes de la academia Shibusen cazan almas para crear armas demoníacas.', 'Shonen', 2004, 'imagen/img_obras/mangas/souleater_1.jpg', 1, 'Norma Editorial'),
('Dorohedoro Vol. 1', 'Caiman, un hombre con cabeza de reptil, busca al hechicero que lo transformó.', 'Seinen', 2000, 'imagen/img_obras/mangas/dorohedoro_1.jpg', 1, 'ECC Ediciones'),
('Golden Kamuy Vol. 1', 'Un veterano de guerra y una joven Ainu buscan un legendario tesoro de oro.', 'Seinen', 2014, 'imagen/img_obras/mangas/goldenkamuy_1.jpg', 1, 'Kitsune Manga'),
('Made in Abyss Vol. 1', 'Una chica y un robot descienden a un abismo lleno de peligros y misterios.', 'Seinen', 2012, 'imagen/img_obras/mangas/abyss_1.jpg', 1, 'Ivrea'),
('Komi-san no puede comunicarse', 'Komi es hermosa pero tiene ansiedad social extrema y quiere hacer 100 amigos.', 'Comedia', 2016, 'imagen/img_obras/mangas/komi_1.jpg', 1, 'Ivrea'),
('Ao Ashi Vol. 1', 'Un talento bruto del fútbol japonés es reclutado por un equipo profesional juvenil.', 'Spokon', 2015, 'imagen/img_obras/mangas/aoashi_1.jpg', 1, 'Norma Editorial'),
('Vagabond Vol. 2', 'Musashi Miyamoto continúa su peligroso camino de la espada.', 'Seinen', 1999, 'imagen/img_obras/mangas/vagabond_2.jpg', 1, 'Ivrea'),
('Berserk Vol. 2', 'Guts continúa su cacería de los apóstoles enfrentándose al Conde.', 'Seinen', 1990, 'imagen/img_obras/mangas/berserk_2.jpg', 1, 'Kitsune Manga'),
('Gantz Vol. 1', 'Personas fallecidas son resucitadas para participar en sádicos juegos de caza extraterrestre.', 'Seinen', 2000, 'imagen/img_obras/mangas/gantz_1.jpg', 1, 'Panini España'),
('Pluto Vol. 1', 'Un detective investiga los asesinatos de los robots más avanzados del mundo.', 'Seinen', 2003, 'imagen/img_obras/mangas/pluto_1.jpg', 1, 'Planeta Cómic'),
('Buenas noches, Punpun Vol. 2', 'Las complejas relaciones familiares de Punpun comienzan a fracturarse.', 'Seinen', 2008, 'imagen/img_obras/mangas/punpun_2.jpg', 1, 'Norma Editorial');

-- ==============================================================================
-- 4. CATEGORÍA: CÓMICS (TIPO 3) - 33 Obras
-- ==============================================================================
INSERT INTO obra (titulo, descripcion, genero, anno_lanzamiento, portada, tipo, nombre_editorial) VALUES 
('El Largo Halloween', 'Batman persigue a un asesino en serie que ataca solo en días festivos.', 'Superhéroes', 1996, 'imagen/img_obras/comics/long_halloween.jpg', 0, 'Norma Editorial'),
('Batman: Silencio (Hush)', 'Un misterioso villano manipula a los enemigos de Batman desde las sombras.', 'Superhéroes', 2002, 'imagen/img_obras/comics/batman_hush.jpg', 0, 'Norma Editorial'),
('La Muerte de Superman', 'El Hombre de Acero se sacrifica para detener al monstruo imparable Doomsday.', 'Superhéroes', 1992, 'imagen/img_obras/comics/death_superman.jpg', 0, 'Norma Editorial'),
('Crisis en Tierras Infinitas', 'El multiverso de DC colapsa ante la amenaza del Anti-Monitor.', 'Superhéroes', 1985, 'imagen/img_obras/comics/crisis_tierras.jpg', 0, 'Norma Editorial'),
('Crisis Final', 'Darkseid logra su objetivo y la realidad misma empieza a sucumbir.', 'Superhéroes', 2008, 'imagen/img_obras/comics/final_crisis.jpg', 0, 'Norma Editorial'),
('El Tribunal de los Búhos', 'Batman descubre una sociedad secreta que ha controlado Gotham por siglos.', 'Superhéroes', 2011, 'imagen/img_obras/comics/court_owls.jpg', 0, 'Norma Editorial'),
('El Asombroso Spider-Man: Spider-Verse', 'Todos los Spider-Men del multiverso se unen contra los Herederos.', 'Superhéroes', 2014, 'imagen/img_obras/comics/spiderverse.jpg', 0, 'Panini España'),
('Secret Wars (2015)', 'El multiverso es destruido y el Doctor Muerte crea el Mundo de Batalla.', 'Superhéroes', 2015, 'imagen/img_obras/comics/secret_wars.jpg', 0, 'Astiberri'),
('Dinastía de M', 'La Bruja Escarlata altera la realidad creando un mundo dominado por mutantes.', 'Superhéroes', 2005, 'imagen/img_obras/comics/house_of_m.jpg', 0, 'Panini España'),
('Lobezno: El Viejo Logan', 'Un Lobezno pacifista viaja por unos Estados Unidos conquistados por villanos.', 'Superhéroes', 2008, 'imagen/img_obras/comics/old_man_logan.jpg', 0, 'Panini España'),
('Marvels', 'La historia del universo Marvel vista a través del lente de un fotógrafo.', 'Superhéroes', 1994, 'imagen/img_obras/comics/marvels.jpg', 3, 'Astiberri'),
('Vengadores: Desunidos', 'El día más oscuro para los Vengadores marca el fin de una era.', 'Superhéroes', 2004, 'imagen/img_obras/comics/avengers_disassembled.jpg', 0, 'Panini España'),
('Infinity War', 'Magus, la mitad malvada de Adam Warlock, amenaza con conquistar el universo.', 'Superhéroes', 1992, 'imagen/img_obras/comics/infinity_war.jpg', 0, 'Astiberri'),
('Aniquilación', 'Una ola destructiva desde la Zona Negativa asola el cosmos de Marvel.', 'Ciencia Ficción', 2006, 'imagen/img_obras/comics/annihilation.jpg', 0, 'Panini España'),
('Planet Hulk', 'Hulk es exiliado al espacio y se convierte en gladiador en Sakaar.', 'Superhéroes', 2006, 'imagen/img_obras/comics/planet_hulk.jpg', 0, 'Astiberri'),
('Hellblazer: Hábitos Peligrosos', 'John Constantine es diagnosticado con cáncer de pulmón e intenta engañar al diablo.', 'Terror', 1991, 'imagen/img_obras/comics/hellblazer_1.jpg', 0, 'Norma Editorial'),
('Predicador Vol. 2', 'Jesse Custer se enfrenta a los pervertidos secretos de su propia familia.', 'Terror', 1996, 'imagen/img_obras/comics/preacher_2.jpg', 0, 'Panini España'),
('Fábulas Vol. 1', 'Los personajes de cuentos de hadas viven exiliados en el Nueva York moderno.', 'Fantasía', 2002, 'imagen/img_obras/comics/fables_1.jpg', 0, 'Norma Editorial'),
('Transmetropolitan Vol. 1', 'El periodista gonzo Spider Jerusalem lucha contra la corrupción en un futuro loco.', 'Ciencia Ficción', 1997, 'imagen/img_obras/comics/transmet_1.jpg', 0, 'Norma Editorial'),
('The Boys Vol. 2', 'El equipo viaja a Rusia para investigar a una corporación mafiosa de superhéroes.', 'Superhéroes', 2007, 'imagen/img_obras/comics/the_boys_2.jpg', 0, 'Norma Editorial'),
('Invencible Vol. 2', 'Mark comienza a descubrir la verdad sobre el imperio Viltrumita.', 'Superhéroes', 2004, 'imagen/img_obras/comics/invincible_2.jpg', 0, 'ECC Ediciones'),
('The Walking Dead Vol. 2', 'El grupo de sobrevivientes se refugia en una prisión abandonada.', 'Terror', 2004, 'imagen/img_obras/comics/twd_2.jpg', 0, 'ECC Ediciones'),
('Paper Girls Vol. 1', 'Un grupo de repartidoras de periódicos queda atrapado en una guerra temporal.', 'Ciencia Ficción', 2015, 'imagen/img_obras/comics/papergirls_1.jpg', 0, 'Planeta Cómic'),
('Locke & Key Vol. 1', 'Tres hermanos se mudan a una mansión llena de llaves mágicas y secretos oscuros.', 'Fantasía', 2008, 'imagen/img_obras/comics/locke_key_1.jpg', 0, 'Astiberri'),
('Scott Pilgrim Vol. 2', 'Scott se enfrenta al actor de Hollywood y skater profesional Lucas Lee.', 'Comedia', 2005, 'imagen/img_obras/comics/scott_pilgrim_2.jpg', 0, 'Debolsillo'),
('Kick-Ass', 'Un adolescente decide convertirse en superhéroe en el mundo real, con brutales consecuencias.', 'Acción', 2008, 'imagen/img_obras/comics/kickass.jpg', 0, 'Panini España'),
('Spawn Vol. 1', 'Un asesino traicionado hace un pacto con el diablo para volver a ver a su esposa.', 'Terror', 1992, 'imagen/img_obras/comics/spawn_1.jpg', 0, 'Planeta Cómic'),
('Tortugas Ninja (TMNT) The Last Ronin', 'La última Tortuga sobreviviente busca venganza en un futuro ciberpunk.', 'Acción', 2020, 'imagen/img_obras/comics/last_ronin.jpg', 0, 'Norma Editorial'),
('Hellboy: Despierta al Demonio', 'Hellboy viaja a Rumania para detener a una vampira y las fuerzas nazis.', 'Terror', 1996, 'imagen/img_obras/comics/hellboy_2.jpg', 0, 'Norma Editorial'),
('Batman: Asilo Arkham', 'Los reclusos de Arkham toman el control y exigen que Batman se una a ellos.', 'Superhéroes', 1989, 'imagen/img_obras/comics/arkham_asylum.jpg', 0, 'ECC Ediciones'),
('Superman: Identidad Secreta', 'Un chico llamado Clark Kent descubre que tiene los poderes del personaje de cómic.', 'Superhéroes', 2004, 'imagen/img_obras/comics/secret_identity.jpg', 0, 'ECC Ediciones'),
('Gideon Falls Vol. 1', 'Un misterio que entrelaza a un sacerdote católico y a un joven obsesionado con la basura.', 'Terror', 2018, 'imagen/img_obras/comics/gideon_falls_1.jpg', 0, 'Astiberri'),
('Monstress Vol. 1', 'Una joven vinculada a un monstruo arcano sobrevive en un mundo matriarcal en guerra.', 'Fantasía', 2015, 'imagen/img_obras/comics/monstress_1.jpg', 0, 'Norma Editorial');

-- ==============================================================================
-- INSERT DE NUEVOS AUTORES (Sin ID, usando autoincrement)
-- ==============================================================================
INSERT INTO autor (nombre, apellidos, email, num_obras) VALUES 
('Stephen', 'King', 'contacto@stephenking.com', 65),
('Gabriel', 'García Márquez', 'contacto@gabomarquz.com', 20),
('J.R.R.', 'Tolkien', 'contacto@jrrtolkien.com', 15),
('J.K.', 'Rowling', 'contacto@jkrowling.com', 25),
('Patrick', 'Rothfuss', 'contacto@patrickrothfuss.com', 3),
('Frank', 'Herbert', 'contacto@frankherbert.com', 22),
('Isaac', 'Asimov', 'contacto@isaacasimov.com', 500),
('Arthur C.', 'Clarke', 'contacto@arthurcclarke.com', 100),
('Dan', 'Simmons', 'contacto@dansimmons.com', 30),
('Suzanne', 'Collins', 'contacto@suzannecollins.com', 10),
('George R.R.', 'Martin', 'contacto@grrmartin.com', 25),
('Elísabet', 'Benavent', 'contacto@elisabetbenavent.com', 22),
('Carlos', 'Ruiz Zafón', 'contacto@carlosruizzafon.com', 8),
('Dan', 'Brown', 'contacto@danbrown.com', 8),
('Ken', 'Follett', 'contacto@kenfollett.com', 30),
('Noah', 'Gordon', 'contacto@noahgordon.com', 10),
('Yoshiyuki', 'Sadamoto', 'contacto@yoshiyukisadamoto.com', 5),
('Naoko', 'Takeuchi', 'contacto@naokotakeuchi.com', 10),
('CLAMP', '', 'contacto@clamp.com', 35),
('Natsuki', 'Takaya', 'contacto@natsukitakaya.com', 15),
('Ai', 'Yazawa', 'contacto@aiyazawa.com', 12),
('Rumiko', 'Takahashi', 'contacto@rumikotakahashi.com', 20),
('Yoshihiro', 'Togashi', 'contacto@yoshihirotogashi.com', 8),
('Nobuhiro', 'Watsuki', 'contacto@nobuhirowatsuki.com', 10),
('Hideaki', 'Sorachi', 'contacto@hideakisorachi.com', 5),
('Hiro', 'Mashima', 'contacto@hiromashima.com', 15),
('Yuki', 'Tabata', 'contacto@yukitabata.com', 3),
('Riichiro', 'Inagaki', 'contacto@riichiroinagaki.com', 8),
('Kaiu', 'Shirai', 'contacto@kaiushirai.com', 5),
('Aka', 'Akasaka', 'contacto@akaakasaka.com', 6),
('Hirohiko', 'Araki', 'contacto@hirohikoaraki.com', 130),
('ONE', '', 'contacto@one.com', 4),
('Yusei', 'Matsui', 'contacto@yuseimatsui.com', 7),
('Atsushi', 'Ohkubo', 'contacto@atsushiohkubo.com', 5),
('Q', 'Hayashida', 'contacto@qhayashida.com', 4),
('Satoru', 'Noda', 'contacto@satorunoda.com', 3),
('Akihito', 'Tsukushi', 'contacto@akihitotsukushi.com', 2),
('Tomohito', 'Oda', 'contacto@tomohitooda.com', 3),
('Yugo', 'Kobayashi', 'contacto@yugokobayashi.com', 6),
('Takehiko', 'Inoue', 'contacto@takehikoinoue.com', 10),
('Kentaro', 'Miura', 'contacto@kentaromiura.com', 5),
('Hiroya', 'Oku', 'contacto@hiroyaoku.com', 8),
('Naoki', 'Urasawa', 'contacto@naokiurasawa.com', 15),
('Inio', 'Asano', 'contacto@inioasano.com', 12),
('Jeph', 'Loeb', 'contacto@jephloeb.com', 40),
('Dan', 'Jurgens', 'contacto@danjurgens.com', 50),
('Marv', 'Wolfman', 'contacto@marvwolfman.com', 60),
('Grant', 'Morrison', 'contacto@grantmorrison.com', 70),
('Scott', 'Snyder', 'contacto@scottsnyder.com', 30),
('Dan', 'Slott', 'contacto@danslott.com', 45),
('Jonathan', 'Hickman', 'contacto@jonathanhickman.com', 30),
('Brian Michael', 'Bendis', 'contacto@brianmichaelbendis.com', 80),
('Mark', 'Millar', 'contacto@markmillar.com', 50),
('Kurt', 'Busiek', 'contacto@kurtbusiek.com', 40),
('Jim', 'Starlin', 'contacto@jimstarlin.com', 35),
('Keith', 'Giffen', 'contacto@keithgiffen.com', 50),
('Greg', 'Pak', 'contacto@gregpak.com', 25),
('Garth', 'Ennis', 'contacto@garthennis.com', 60),
('Bill', 'Willingham', 'contacto@billwillingham.com', 25),
('Warren', 'Ellis', 'contacto@warrenellis.com', 55),
('Robert', 'Kirkman', 'contacto@robertkirkman.com', 30),
('Brian K.', 'Vaughan', 'contacto@briankvaughan.com', 20),
('Joe', 'Hill', 'contacto@joehill.com', 15),
('Bryan Lee', 'O''Malley', 'contacto@bryanleeomalley.com', 6),
('Todd', 'McFarlane', 'contacto@toddmcfarlane.com', 40),
('Kevin', 'Eastman', 'contacto@kevineastman.com', 20),
('Mike', 'Mignola', 'contacto@mikemignola.com', 30),
('Jeff', 'Lemire', 'contacto@jefflemire.com', 25),
('Marjorie', 'Liu', 'contacto@marjorieliu.com', 15),
('Domingo', 'Villar', 'contacto@domingovillar.com', 4);